### ISSUE TITLE
Resolve '413Request Entity Too Large' issue with uuid-api 

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/gateway#156]
From Ivan:

>I am trying to generate UUIDS using the uuid-api however my curl command returns this message. Any elegant solutions (or magic) that would help without having to partition my json package into blocks?

>curl -X POST -d @- -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" https://uuid-api.dev.hubmapconsortium.org/hmuuid\?entity_count\=6950 < obi_0002631-_hive_hubmap_data_protected_University_of_Florida_TMC_8776e9183d5f85d90535a0b1b3b4e32a.txt

The POST is a big json:
[obi_0002631-_hive_hubmap_data_protected_University_of_Florida_TMC_8776e9183d5f85d90535a0b1b3b4e32a.txt](https://github.com/hubmapconsortium/gateway/files/7809529/obi_0002631-_hive_hubmap_data_protected_University_of_Florida_TMC_8776e9183d5f85d90535a0b1b3b4e32a.txt)

**Comment by shirey** [comment]
@icaoberg Closing this, let us know if you still have problems.
