### ISSUE TITLE
Publish PROD AWS services behind AWS API Gateway

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/gateway#157]

**Comment by yuanzhou** [comment]
To be addressed via the following PRs:
- https://github.com/hubmapconsortium/gateway/pull/160
- https://github.com/hubmapconsortium/entity-api/pull/283
- https://github.com/hubmapconsortium/search-api/pull/432
- https://github.com/hubmapconsortium/uuid-api/pull/48

Workflow documentation and Lambda functions/layer: [aws-api-gateway](https://github.com/hubmapconsortium/aws-api-gateway)
