### ISSUE TITLE
Increase the proxy timeout to facilitate portal-ui's handling on slow Cells API

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/gateway#158]
From Chuck:
>We’re planning to increase the timeout between the portal-ui nginx and uwsgi, so that slow requests to the Cells API will not time out. 
 https://github.com/hubmapconsortium/portal-ui/pull/2321

From Zhou:
> the gateway will need to use the same or greater timeout for portal-ui proxy. The default is 60 seconds. We can increase to 300 for example or even more depending what portal-ui's nignx will be using. I may also need to add the following to gateway nginx:
proxy_connect_timeout 300;
keepalive_timeout 300 300;
proxy_read_timeout 300;
proxy_send_timeout 300;
I'll need to look into these settings and use the correct ones when gateway nginx forwards the requests to portal-ui nginx. 

From Chuck:
> The only setting I’m changing is uwsgi_read_timeout , but I expect the setting to change on your side is something different… I’ve chosen 600, but the precise number isn’t critical: 300 should be fine.
Let me know if you need anything else, and let us know when the work is complete. (Or point me to an issue that you’ll use to track this work.)

**Comment by shirey** [comment]
Retest once the Cells API is behind the AWS API Gateway

**Comment by yuanzhou** [comment]
According to Sean:

>Yeah, I think for the most part, the timeout issues are resolved.

**Comment by yuanzhou** [comment]
Already addressed in the Nginx config
