### ISSUE TITLE
Ingest API behind AWS Gateway

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/gateway#161]

**Comment by yuanzhou** [comment]
Resource from Matt: https://aws.amazon.com/blogs/security/how-to-enhance-amazon-cloudfront-origin-security-with-aws-waf-and-aws-secrets-manager/

**Comment by yuanzhou** [comment]
- Add WAF ACL and attach to API Gateway to control IPs
- Create lambda function to forward requests to API running on PSC VM
- Create NAT in the current VPC with private subnet and associate with the lambda function
- PSC VM only allow the Elastic IP of the private subnet

**Comment by yuanzhou** [comment]
Can not get lambda to handle the globus redirection correctly.

Current implementation:
Domain -> AWS WAF (IP set rules) -> AWS API Gateway -> NLB -> Target group ("old" gateway proxy) -> PSC VM.

And PSC firewall rules only allows inbound traffic from the EC2 instance per each deployment.

**Comment by yuanzhou** [comment]
@shirey I had this working using the AWS API Gateway to handle ingest-api on PSC, but we never really finalize and finish this work due to ongoing requests. Not sure if this is still a goal.

**Comment by shirey** [comment]
Won't implement
