### ISSUE TITLE
Upgrade from Python 3.6 in base image

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/gateway#191]
I think the change is needed [here](https://github.com/hubmapconsortium/gateway/blob/test-release/api-base-image/Dockerfile#L14).

- [3.6 has reached end of life](https://www.python.org/downloads/release/python-360/)
- and [it's blocking search-api work](https://github.com/hubmapconsortium/search-api/pull/467#issuecomment-1083258927)

The problem is that code that is wrapped up for Docker _is also_ run on a bare VMs. Joel writes:
> The constraint to 3.6 arises from what's available for CentOS 7, which is the OS run by the existing HIVE worker nodes l00[1,2], gpu000, and the hivevm hosts.  It's quite annoying but it will be difficult to migrate the Airflow infrastructure to a better Python before we jump to new hardware.
> ...
> There’s a timeline, but it’s written in months, not days.

**Comment by yuanzhou** [comment]
Also note PSC is in the process of migrating to RedHat 8, but will take some time.
