### ISSUE TITLE
Add workspaces to status.json

### ISSUE THREAD

**Issue by jpuerto-psc** [hubmapconsortium/gateway#224]
Please update the status.json to grab status from workspaces API:

DEV: https://workspaces-api.dev.hubmapconsortium.org/status
PROD: https://workspaces.api.hubmapconsortium.org/status

**Comment by yuanzhou** [comment]
@jpuerto-psc @mccalluc since we only have workspaces-api on DEV and PROD, would it be Okay if we configure gateway to point to the DEV url of workspaces-api on TEST and STAGE as well?

**Comment by jpuerto-psc** [comment]
@yuanzhou this is okay with me, at least until we get this deployed on TEST and STAGE.

**Comment by yuanzhou** [comment]
Already addressed
