### ISSUE TITLE
Assets service broken for Publications

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/gateway#240]
The assets service for Publication entities should work exactly the same as for Datasets.  Currently the following requests (including a valid Auth Bearer token) are failing with 500s. One on DEV, one on TEST:

```
https://assets.dev.hubmapconsortium.org/89af89aa5b12a75fe84d441ef1df5b45/test-file.txt

https://assets.test.hubmapconsortium.org/efc91b624ff572ad4f991cf8fc2a36ef/data/vignette_scrnaseq/A/0/b359b84b-5c31-49ae-bb6f-537baf9e76dc/X/data/1
```

**Comment by yuanzhou** [comment]
Already fixed and released via https://github.com/hubmapconsortium/gateway/commit/731653d23524b39acc561cbdd353e4e9750496c1
