### ISSUE TITLE
UMLS authorized assets download

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/gateway#308]
Add additional functionality in the assets service to authorize a download from a directory `umls-download/` under the existing `../assets` directory.  Any file downloaded via the assets service starting with the directory `/umls-download/` should be authorized via the [hubmap-auth service](https://github.com/hubmapconsortium/gateway/tree/main/hubmap-auth).  This will require a non-optional parameter to be added to the end of the URL, `?umls-key=<key>`, for the user to provide their UMLS License Key.  This key will be used to authorized the user via the service: `https://utslogin.nlm.nih.gov/validateUser?validatorApiKey=<hubmap-umls-api-key>&apiKey=<key>` which must return `true`, otherwise return a 403.

**Comment by yuanzhou** [comment]
Update 4/16/2024

@DerekFurstPitt rename to `/ubkg-download`
