### ISSUE TITLE
HEAD Method Returns 401

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/gateway#76]
@yuanzhou  Following up on slack, I think I figured out the issue.

Would it be possible to support HEAD as an auth-ed method for the `assets` API?

For example

```bash
curl --request HEAD -i -H "Authorization: Bearer XXX_MY_TOKEN_XXX" -H "Content-Type: application/json" https://assets.test.hubmapconsortium.org/73c8693778dc87eb7be2f905f0565a00/hubmap_ui/anndata-zarr/secondary_analysis.zarr/obs/__categories/marker_gene_0/.zgroup
```

returns a 401 at the moment.  If not, no worries, it's not a blocker, we will try not make HEAD requests.

**Comment by yuanzhou** [comment]
Currently any request methods other than GET will return 401. It should be easy to treat HEAD requests as auth-ed without doing any additional lookups or checks. Can you explain a bit more about the use case?

**Comment by ilan-gold** [comment]
It's very non-crucial and avoidable but here are some details: https://github.com/gzuidhof/zarr.js/blob/375ce0c299469a970da6bb5653513564e25806bb/docs/getting-started/remote-data.md#stores

This library makes lots of small requests, a non-negligible subset of which are often 404's so it can be faster to just use `HEAD` than a full `GET`

**Comment by yuanzhou** [comment]
I see. Using HEAD in this case to get back some metadata information without the actual download is definitely faster than GET. I’ll try to incorporate this support into the next release.

**Comment by yuanzhou** [comment]
@ilan-gold have you verified the HEAD support on TEST? I did some quick testing and seems to be working fine.

**Comment by ilan-gold** [comment]
I seem to be having a CORS issue of some sort.  It seems that the access-control-allow-origin response header is not on these HEAD 404s.  Maybe I am misunderstanding though.  I will try to reproduce

**Comment by ilan-gold** [comment]
Console error:
<img width="1478" alt="Screen Shot 2021-03-23 at 9 58 41 AM" src="https://user-images.githubusercontent.com/43999641/112158287-6507f700-8bbe-11eb-8c2e-b57c7d53f7de.png">
`HEAD` 404:
<img width="420" alt="Screen Shot 2021-03-23 at 9 58 02 AM" src="https://user-images.githubusercontent.com/43999641/112158198-53beea80-8bbe-11eb-941c-1a89b7c81d92.png">
`GET` 404:
<img width="428" alt="Screen Shot 2021-03-23 at 9 56 59 AM" src="https://user-images.githubusercontent.com/43999641/112158211-54f01780-8bbe-11eb-9503-e8d4e1e7443f.png">

**Comment by yuanzhou** [comment]
Added CORS support for HEAD on file assets service.
